server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql-customer:3306/customerdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
